name: first workflow
on: workflow_dispatch
jobs:
  first_job:
    runs_on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "hello greeting"
      - name: pring bye
        run: echo "goodbye"
